# Generated by Django 3.2.5 on 2021-11-24 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_created_by', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payee', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
