# Generated by Django 3.2.5 on 2021-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_expense', '0002_alter_expense_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Group', 'Group'), ('Friend', 'Friend')], default='Friend', max_length=128),
        ),
    ]
